version: '3'

services:
  web:
    build:
      # indicate where the file are located
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - .:/app

  tests:
    build:
      # indicate where the file are located
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ['yarn', 'run', 'test']
